### ISSUE TITLE
Participant.getSummoner returns null

### ISSUE THREAD

**Issue by EntilZha** [robrua/Orianna#12]
Found something else that seems like a bug. Using  `Participant` from `RiotAPI.getMatch`, the following code results in a null value, which then throws null pointer on attempting to access its fields

```scala
val participant: Participant = ...
val summoner = participant.getSummoner
// At this point summoner is null, so the calls below fail
summoner.getID
summoner.getMatchHistory
// So on and so forth
```

Like last issue, more than willing to help out, but not familiar with code base.

**Comment by robrua** [comment]
This is the intended behavior. For a lot of matches Riot just doesn't send the identifying information for a summoner.
