### ISSUE TITLE
Setting locale parameter

### ISSUE THREAD

**Issue by gcmorrison** [robrua/Orianna#13]
Hi, I recently started using your library.  I really like what you are doing with this, but I have one problem.  There is no way for me to set the locale in the request.  I want to support all the languages, regardless of which Region the user is playing on.  Any chance you can add it?  Even if it's just RiotApi.setLocale(), which will add the locale as a parameter to every call.  

Please!

**Comment by robrua** [comment]
Hey,

I'll look into adding this soon.

**Comment by robrua** [comment]
Just added it in version 2.5.5.

**Comment by gcmorrison** [comment]
Awesome, thanks :+1:
