### ISSUE TITLE
Display Champion Image

### ISSUE THREAD

**Issue by JeffreyCA** [robrua/Orianna#25]
I have a list of Participants, `List<Participant> participants` containing 10 participants and I want to create an `ImageView` that contains the champion image/picture.

`Image img = participants.get(0).getChampion().getImage();`

Now how would I use `img` to have it display on the ImageView? I haven't found a way to convert the `Image img` into a bitmap.

**Comment by robrua** [comment]
The Image type doesn't actually store the image data, so you won't be able to find a way to convert it directly into a bitmap.

https://developer.riotgames.com/docs/static-data describes how to get the images from the Image data the API sends under the Image & Data Urls section.

**Comment by JeffreyCA** [comment]
Yeah, that's what I ended up doing, thanks though.
