### ISSUE TITLE
Summoner Level, Rank, etc are not loaded before hand using UPFRONT load policy

### ISSUE THREAD

**Issue by JeffreyCA** [robrua/Orianna#26]
I load a CurrentGame and its Participants, with `LoadPolicy.UPFRONT`. When I call `participants.get(pos).getSummoner().getLevel();`, or `participants.get(pos).getSummoner().getLeagues()`, they are not loaded before hand it has to query Riot's API servers.

**Comment by JeffreyCA** [comment]
Is this a bug or is it intended?

**Comment by robrua** [comment]
I can't replicate the API making another call on participants.get(pos).getSummoner().getLevel(); with UPFRONT loading.

As far as the getLeagues() call goes, this is the intended behavior. Leagues aren't a FK value sent by a different call, so they aren't filled in by upfront loading. summoner.getLeagues() is a convenience shortcut for RiotAPI.getLeagues(summoner);

Here's the approach for getting ranks and LP:
for(League league : summoner.getLeagueEntries()){
            LeagueEntry entry = league.getParticipantEntry();
            System.out.println(league.getQueueType() + ": " + league.getTier() + " " + entry.getDivision() + " " + entry.getLeaguePoints() + " LP");
        }

**Comment by JeffreyCA** [comment]
Thank you!
