### ISSUE TITLE
IllegalArgumentException when using getStats()

### ISSUE THREAD

**Issue by JeffreyCA** [robrua/Orianna#27]
For some summoners, I get an error:

`java.lang.IllegalArgumentException: Bilgewater is not a constant in com.robrua.orianna.type.core.stats.PlayerStatsSummaryType` when I perform `getStats()`

You probably did not account for the new gamemode Bilgewater.

**Comment by robrua** [comment]
You probably didn't switch to one of the newer versions that were released after the Bligewater gamemode started existing.

https://github.com/robrua/Orianna/commit/167156489a184890d51b0e88d88f30a9567645c5
