### ISSUE TITLE
Summoner.getRecentGames fails if match contains an item that has since been removed

### ISSUE THREAD

**Issue by ccitro** [robrua/Orianna#3]
In 4.21, Riot removed Atma's Impaler from the game.  Since then, If I call Summoner.getRecentGames it will throw an exception because the call to https://global.api.pvp.net/api/lol/static-data/na/v1.2/item/3005 returns a 404 HTTP response code.

This may only happen for summoners who have recent games in which a player purchased the item, but I haven't tested that.

I'm not particularly interested in the item data for my specific use case, so lazy-loading the item data would both speed up the method and circumvent the issue for me.  However, for users who do need item data for the match, some sort of solution that gracefully handles the removal of items from the game will be needed.

**Comment by robrua** [comment]
Added ignored item list to getItem() method in RiotAPI for now. This shouldn't be the permanent fix, but should work for now.

**Comment by robrua** [comment]
v2 Lazy loading mitigates this problem, ignored items are still around to avoid unnecessary API calls.
