### ISSUE TITLE
Combined Stats from Runes

### ISSUE THREAD

**Issue by JeffreyCA** [robrua/Orianna#30]
I have a `List<RuneCount>` called `runeCount`.
Right now this code just displays the number and the name of a rune a summoner has. How would I gather the combined stats from the runes? (Like how much additional armor, ad, ap, etc. the player gets from his runes)

```
String text = "";

for (int i = 0; i < runeCount.size(); i++) {
     text += runeCount.get(i).getRune().getName() + " " + runeCount.get(i).getCount() + "x \n";
}
```
Do I use `runeCount.get(i).getRune().getStats()` ?

**Comment by robrua** [comment]
What is a RuneCount? It looks like you may be talking about RuneSlot instead.

```java
runeSlot.getRune().getStats()
```
will give you the stats for the Rune as sent by the Riot API (unfortunately some of the stats aren't properly included in what Riot sends and may be missing).

You can sum these over the entire RunePage to get aggregate stats for it.

**Comment by JeffreyCA** [comment]
I got runeCount from: `final List<RuneCount> runeCount = participants.get(position).getRunes();`

**Comment by robrua** [comment]
Nope, seems fine. I'd just forgotten that type existed. You should be able to access the stats with getRune().getStats() as you thought

**Comment by JeffreyCA** [comment]
Ok, so I think I have to run each rune through all of these methods listed [here](http://robrua.github.io/Orianna/com/robrua/orianna/type/core/staticdata/BasicDataStats.html#BasicDataStats-com.robrua.orianna.type.dto.staticdata.BasicDataStats-)?

**Comment by robrua** [comment]
As things are now, yes. You should also multiply by the count in the RuneCount.

**Comment by JeffreyCA** [comment]
Got it, thank you

**Comment by JeffreyCA** [comment]
Sorry, one quick question, what does the Mod mean in `getFlatArmorMod()`, `getFlatCritChanceMod()`, etc, ?

**Comment by JeffreyCA** [comment]
Also, do you think I should create a double variable for each stat (71 of them)?
