### ISSUE TITLE
getRPercentCooldownMod(), getFlatCritChanceMod()

### ISSUE THREAD

**Issue by JeffreyCA** [robrua/Orianna#31]
Do those two methods return a double *no greater* than 1.00 or a double *no greater* than 100?

In other words, if someone has +5% critical chance runes, does the method `getFlatCritChanceMod()` return 0.05 or 5?

**Comment by robrua** [comment]
In your example 0.05 would be returned.

By the way, if you could just test simple stuff like this yourself in the future instead of opening an issue that'd be great =D. I'm just going to go in and test it myself the same way you would anyway.
