### ISSUE TITLE
Unused BasicDataStats

### ISSUE THREAD

**Issue by JeffreyCA** [robrua/Orianna#33]
In your API, there are [70 different rune statistics](http://robrua.github.io/Orianna/com/robrua/orianna/type/core/staticdata/BasicDataStats.html), but in Riot's API documentation there are only [65](https://developer.riotgames.com/api/methods#!/968/3315).

**Comment by robrua** [comment]
BasicDataStats is shared with Items, where some extra parsing of descriptions is done to extract stats that aren't sent by the API but that the item has.
