### ISSUE TITLE
Masteries getRank() does not return correct number of points

### ISSUE THREAD

**Issue by JeffreyCA** [robrua/Orianna#34]
I have the following code to get the masteries of a Participant.

		List<MasteryRank> mr = participant.getMasteries();

		for (int j = 0; j < mr.size(); j++) {
			String mastery = mr.get(j).getMastery().getName();
			int rank = mr.get(j).getMastery().getRanks();
			System.out.println(mr.get(j).getMasteryID() + " " + rank);
		}

The output is:
```
4133 1
4134 3
4141 1
4143 3
4144 1
4152 3
4154 1
4162 1
4211 2
4212 2
4213 2
4221 1
4222 3
4232 1
```

The `rank` does not return the correct number of points the player put into his mastery page. Instead, it returns the maximum number of points for each mastery the player is using.

Also, shouldn't the code above include masteries that the summoner is not using and return zero for the getRank()?

**Comment by robrua** [comment]
You're code isn't doing what you think it's doing. You're calling mastery.getRanks(), which returns how many ranks a mastery has. You want to be calling participantMastery.getRank(), which returns the rank that a participant has that mastery at.

I don't see why a list of masteries that a participant is using should include the full list of masteries. If you'd like a full list of masteries call RiotAPI.getMasteries().

**Comment by JeffreyCA** [comment]
How do you get participantMastery from a CurrentGame or Participant?

**Comment by robrua** [comment]
line 5:
mr.get(j).getMastery().getRanks(); -> mr.get(j).getRank();

**Comment by JeffreyCA** [comment]
Thanks!
