### ISSUE TITLE
AggregatedStats

### ISSUE THREAD

**Issue by JeffreyCA** [robrua/Orianna#37]
Is there a way to get `AggregatedStats` for a summoner `s`?

**Comment by robrua** [comment]
s.getRankedStats() gives Map<Champion, ChampionStats>. In this, null maps to combined stats for all champions. championStats.getStats() gives AggregatedStats

**Comment by JeffreyCA** [comment]
Yes that's for Ranked Stats, but what about for player stat summaries in general (not only ranked)? I'm talking about [this](https://developer.riotgames.com/api/methods#!/1018/3453). You can specify the queue type and it returns a summary of information for that type.

**Comment by robrua** [comment]
getStats() rather than getRankedStats() corresponds to that endpoint.
