### ISSUE TITLE
NullPointerException if a summoner did not exist in particular Season

### ISSUE THREAD

**Issue by JeffreyCA** [robrua/Orianna#39]
The following code gets a player's ranked stats (Wins/Losses) for all the possible seasons. `getStats(Season)` does not accept `Season.PRESEASON****` and returns `BAD_REQUEST (400) error` as I have stated [here](https://github.com/robrua/Orianna/pull/38).

If a summoner has not played a ranked game in Season 4 (so no data of ranked solo queue), but has played other game modes for example, then `mss.containsKey(PlayerStatsSummaryType.RankedSolo5x5)` would return false. The map would not be null as there may be other elements in the map.

If a summoner account was created in Season 5, meaning he/she has not played a game in Season 4 or 3, the following code gives `NullPointerException`:
`Map<PlayerStatsSummaryType, PlayerStatsSummary> mss = s.getStats(seas);`
I'm assuming it's because there is no such data of the player in Season 3 or 4.

Here is my full code:
```
for (Season seas : Season.values()) {                               
	if (seas == Season.PRESEASON2014 || seas == Season.PRESEASON2015
			|| seas == Season.PRESEASON3) {                         
		continue;                                                   
	}                                                               
                                                                    
	System.out.println(seas.name());                                
	Map<PlayerStatsSummaryType, PlayerStatsSummary> mss = s         
			.getStats(seas);                                        
                                                                    
	if (mss.containsKey(PlayerStatsSummaryType.RankedSolo5x5)) {    
		totalWins += mss.get(PlayerStatsSummaryType.RankedSolo5x5)  
				.getWins();                                         
		totalLosses += mss.get(PlayerStatsSummaryType.RankedSolo5x5)
				.getLosses();                                       
	}                                                                                                      
}
```

Is this something that you can fix? Or is there a workaround?

I tested this on Riot's API page. My LOL account was created in Season 4, and when I input my ID [here](https://developer.riotgames.com/api/methods#!/1018/3453) for Season 3, the response body is empty: `{"summonerId": XXXXXXXX}` (I removed my actual summonerid)

**Comment by robrua** [comment]
This should now return null instead of failing on an internal null pointer exception in version 2.3.3.
