### ISSUE TITLE
Getting summoner current tier

### ISSUE THREAD

**Issue by Defa1t** [robrua/Orianna#40]
Hi, looking at the API I can see methods for getting a Participants previous highest ranked tier, but no current. Do you know how I'd go about getting that?

Thanks

**Comment by Defa1t** [comment]
Nevermind, looked at riot API and filled in the blanks.

For future reference use .get(0) alot 
`summoner.getLeagues().get(0).getTier()`

**Comment by Defa1t** [comment]
Made a method to get summoner's current rank for anyone who wonders upon this

`    public static String getRank(Summoner summoner){
    	String str = "";
    	List<LeagueEntry> leagueEntries = summoner.getLeagues().get(0).getEntries();
    	String tier = summoner.getLeagues().get(0).getTier().toString();
    	for(LeagueEntry x:leagueEntries){
    		if(x.getSummoner().equals(summoner)){
    			System.out.print(tier + " " + x.getDivision() + ", " + x.getLeaguePoints() + " LP");
    		}
    	}
		return str;
    }`

**Comment by Defa1t** [comment]
I made a method, if anyone wonders upon this trying to find the same info

    public static String getRank(Summoner summoner){
		String str = "";
	  	List<LeagueEntry> leagueEntries = summoner.getLeagues().get(0).getEntries();
	   	String tier = summoner.getLeagues().get(0).getTier().toString();
	   	for(LeagueEntry x:leagueEntries){
	   		if(x.getSummoner().equals(summoner)){
	   			System.out.print(tier + " " + x.getDivision() + ", " + x.getLeaguePoints() + " LP");
	   		}
	   	}
		return str;
	}

output:
`GOLD IV, 100 LP`

**Comment by robrua** [comment]
One note on this - if you use getLeagueEntries instead of getLeague it'll return leagues with only one entry for the summoner you asked for.
