### ISSUE TITLE
New Queue Type

### ISSUE THREAD

**Issue by evanhk** [robrua/Orianna#44]
Any chance you can add the new queue ( TEAM_BUILDER_DRAFT_RANKED_5x5 ) to the QueueType?

**Comment by robrua** [comment]
https://github.com/robrua/Orianna/commit/30aa646f89ed243e67bfb1aae3ae0296f728e781

**Comment by evanhk** [comment]
How did I miss that???
Thanks

**Comment by robrua** [comment]
No worries! It'll be in the next release, but you can get a snapshot @ robrua.com/orianna for now.

**Comment by CSDragon** [comment]
I have the most recent jar, but it's giving me this issue.

**Comment by robrua** [comment]
Hey - looks like that distribution page didn't get the updated .jar for some reason. There's a new one up that should work.
